#The --device, --cap-add and --security-opt options and their values are to make sure that 
#the container will be able to make available the WebDAV resource using FUSE

version: "3.8"
services:
  webdav:
    build:
      context: ./webdavfs/
      dockerfile: Dockerfile
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
    security_opt:
      - "apparmor=unconfined"
    
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      ONEDRIVE_URL: ${ONEDRIVE_URL}
    
    command: ./check-mount-each-min.sh